[package]
name = "simple-chart"
version = "0.7.6"
authors = ["serejkaaa512 <5125402@mail.ru>"]

[[bin]]
name = "main"
doc = false

[dependencies]
byteorder = "0.5.1"
quick-error = "1.1.0"
clippy = {version = "*", optional = true}

[features]
default = []
dev = ["clippy"]